### ISSUE TITLE
Feature Request: provide a migration tool for Pod Security Policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#105]
### Is your feature request related to a problem?

Starting from Kubernetes 1.25, Pod Security Policies are going to be dropped. Users can replace them using Kubewarden policies. However these users would have to learn which Kubewarden policies to use and how to configure them to replicate their current PSPs deployments.

### Solution you'd like

The desired workflow would be to have a user run a script that will:

* Find all the PSPs currently defined inside of a Kubernetes cluster
* Propose Kubewarden Policies to replace them
* When not run in `dry-run`, deploy the Kubewarden Policies into the cluster

The tool should print out yaml files of Kubewarden ClusterAdmissionPolicy objects to be defined.

### Alternatives you've considered

The AppVia folks created [this](https://github.com/appvia/psp-migration) migration tool that does the majority of the work. We would like to offer something more automated, as opposed to copy and paste things into a web UI or [pipe kubectl](https://github.com/appvia/psp-migration#usage) on the cli.

### Anything else?

The desired outcome would be:

* Provide clear instructions about the steps to be performed
* Provide a script (even a bash one) that leverages the [`psp-migration`](https://github.com/appvia/psp-migration) cli
* The script must have a `dry-run` mode that just outputs the resources that would be created inside of the cluster

**Comment by jvanz** [comment]
Considering that we will run  this script only on Linux machines, this is an initial draft of a bash script for this tasks:

```bash
#!/bin/bash

PSP_MIGRATION_TOOL_VERSION=v1.33.287
LOCAL_PSP_MIGRATION_TOOL_PATH=psp-migration
DRY_RUN="false"
HELP="false"

for arg in "$@"
do
  case "$arg" in
    --dry-run)    DRY_RUN="true"
            ;;
    --help)     HELP="true"
            ;;
    esac
done

if [ "$HELP" = "true" ];
then
        echo ""
        echo "This script is used to migrate the PodSecurityPolicy running in your Kubernetes cluster into Kubewarden policies."
        echo "The available options are:"
        echo ""
        echo -e "\t --dry-run: migrate all your PodSecurityPolicy but do _NOT_ apply them. The migrated policies will be saved into a file"
        echo -e "\t --help: show this help message"
        exit 0
fi

if [ ! -x $LOCAL_PSP_MIGRATION_TOOL_PATH ] 
then
        echo "Downloading PSP migration tool... This can take some minutes."
        curl -L -s -o psp-migration "https://github.com/appvia/psp-migration/releases/download/$PSP_MIGRATION_TOOL_VERSION/psp-migration-linux-x64" > /dev/null
        chmod +x psp-migration
fi

echo "Migrating PSPs to Kubewarden policies..."
kubectl get PodSecurityPolicy -A -o yaml 2>&1 > /dev/null | ./psp-migration -e kubewarden > policies.yaml
echo "Yours policies are defined in the file \"policies.yaml\""

if [ "$DRY_RUN" = "false" ];
then
        kubectl apply -f policies.yaml
fi

```

If we decide to do more complex stuff then just redirect command output and applying the files, I would say we need to use other language (e.g. go, rust, python). Bash get complicated and unreadable too fast...

**Comment by jvanz** [comment]
Does the draft script make sense to you, @kubewarden/kubewarden-developers ?

**Comment by viccuad** [comment]
It looks good! I would `set -e` and make it fully POSIX `sh` compatible, too:
```diff
1c1,3
< #!/bin/bash
---
> #!/usr/bin/env sh
>
> set -e
24,25c26,27
<         echo -e "\t --dry-run: migrate all your PodSecurityPolicy but do _NOT_ apply them. The migrated policies will be saved into a file"
<         echo -e "\t --help: show this help message"
---
>         echo "     --dry-run: migrate all your PodSecurityPolicy but do _NOT_ apply them. The migrated policies will be saved into a file"
>         echo "     --help: show this help message"
```

I've run it locally, and it creates a kubewarden psp-volumes and psp-usergroup with empty settings,

In the case of psp-volumes, settings is an allowlist, which we are leaving empty, therefore having a more stringent approach to security. The [psp k8s docs](https://kubernetes.io/docs/concepts/security/pod-security-policy/#volumes-and-file-systems), recomends a short list (ConfigMaps, Secrets, PersistentVolumeClaims..). I wonder if people just firing the thing will not realize about this, even if it is good that we are more strict.

**Comment by raulcabello** [comment]
I like this approach, however I think there is something we have to fix in this script.
As Victor pointed out just `psp-volumes` and `psp-usergroup` policies are created, and they have empty strings. Other policies are not created. 
I believe the problem is in this line
`kubectl get PodSecurityPolicy -A -o yaml 2>&1 > /dev/null | ./psp-migration -e kubewarden > policies.yaml`

I created the following psp:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-security-policy-restricted-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  allowedHostPaths:
    # This allows "/foo", "/foo/", "/foo/bar" etc., but
    # disallows "/fool", "/etc/foo" etc.
    # "/foo/../" is never valid.
    - pathPrefix: "/foo"
      readOnly: true  # only allow read-only mounts
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  # Required to prevent escalations to root.
  requiredDropCapabilities:
    - ALL
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
```

If I run the script just `psp-volumes` and `psp-usergroup` policies are created with empty settings, which is not correct.
However if I execute `kubectl get psp -o yaml pod-security-policy-restricted-psp | ./psp-migration -e kubewarden` all policies are created, and `psp-volumes` and `psp-usergroup` have the settings field properly filled.
